# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('idcard', models.CharField(max_length=20, verbose_name='身份证号码')),
                ('department', models.CharField(choices=[('管理部', '管理部'), ('营销部', '营销部'), ('财务部', '财务部'), ('业务部', '业务部'), ('管理部', '管理部')], max_length=50, verbose_name='部门')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='薪资')),
                ('tel', models.CharField(max_length=20, verbose_name='电话')),
                ('postal_code', models.CharField(max_length=6, verbose_name='邮编')),
                ('birthdate', models.DateField(verbose_name='生日')),
            ],
            options={
                'ordering': ['department', '-salary'],
            },
        ),
    ]
